{\rtf1\ansi\ansicpg1252\cocoartf1348\cocoasubrtf170
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural

\f0\fs24 \cf0 do ->\
\
  AutoSelect = (options) ->\
    @options = if options != null then options else \{\}\
    @$input = $(@options['input'])\
    @width = @options['width'] or 240\
    @placeholder = @options['placeholder']\
    return\
\
  AutoSelect::init = ->\
    scope = undefined\
    url = undefined\
    scope = @$input.attr('data-scope')\
    url = @$input.attr('data-url')\
    @$input.select2\
      placeholder: @placeholder\
      allowClear: true\
      minimumInputLength: 1\
      width: @width\
      ajax:\
        url: url\
        quietMillis: 300\
        data: (term, page) ->\
          \{\
            q: term\
            page_limit: 10\
            page: page\
            scope: scope\
          \}\
        results: (data, page) ->\
          more = undefined\
          more = data.length >= 10\
          \{\
            results: data\
            more: more\
          \}\
      formatResult: ((_this) ->\
        (item, container, query, escapeFn) ->\
          markup = undefined\
          text = undefined\
          markup = []\
          window.Select2.util.markMatch _this.detailText(item), query.term, markup, escapeFn\
          text = markup.join('')\
      )(this)\
      formatSelection: ((_this) ->\
        (item, container, escapeFn) ->\
          _this.detailText item\
      )(this)\
      initSelection: ((_this) ->\
        (e, callback) ->\
          id = undefined\
          id = $(e).val()\
          if id != ''\
            return $.getJSON(url, id: id).done((data) ->\
              callback data\
              _this.$input.trigger 'autocomplete:ajax:success', data\
            )\
          return\
      )(this)\
    @$input.change 'select2-selecting', ->\
      $(this).closest('.filter_form').submit()\
\
  AutoSelect::detailText = (item) ->\
    _.reject(_.uniq(_.toArray(item)), (el) ->\
      el == ''\
    ).join ' - '\
\
  AutoSelect\
# ---\
# generated by coffee-script 1.9.2\
\
# ---\
# generated by js2coffee 2.1.0}